//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEvaBdProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filme()
        {
            this.GenFilmes = new HashSet<GenFilme>();
            this.ProgramariFilmes = new HashSet<ProgramariFilme>();
            this.TipulFilmuluis = new HashSet<TipulFilmului>();
        }
    
        public int IdFilm { get; set; }
        public string Nume { get; set; }
        public double Rating { get; set; }
        public Nullable<int> Varsta_minima { get; set; }
        public string Poze { get; set; }
        public string Trailer { get; set; }
        public string Distributie { get; set; }
        public string Limba_nativa { get; set; }
        public string Regizor { get; set; }
        public string Descriere { get; set; }
        public Nullable<int> Durata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenFilme> GenFilmes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramariFilme> ProgramariFilmes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipulFilmului> TipulFilmuluis { get; set; }
    }
}
