//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEvaBdProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenFilme
    {
        public int IdFilm { get; set; }
        public int IdGen { get; set; }
        public int Cheie { get; set; }
    
        public virtual Filme Filme { get; set; }
        public virtual Genuri Genuri { get; set; }
    }
}
