//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEvaBdProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocuriSali
    {
        public int IdProgramare { get; set; }
        public int NrLoc { get; set; }
        public int State { get; set; }
    
        public virtual ProgramariFilme ProgramariFilme { get; set; }
    }
}
