//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEvaBdProj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Marcel : DbContext
    {
        public Marcel()
            : base("name=Marcel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Filme> Filmes { get; set; }
        public virtual DbSet<GenFilme> GenFilmes { get; set; }
        public virtual DbSet<Genuri> Genuris { get; set; }
        public virtual DbSet<ProgramariFilme> ProgramariFilmes { get; set; }
        public virtual DbSet<Sali> Salis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipuri> Tipuris { get; set; }
        public virtual DbSet<Angajati> Angajatis { get; set; }
        public virtual DbSet<LocuriSali> LocuriSalis { get; set; }
        public virtual DbSet<TipulFilmului> TipulFilmuluis { get; set; }
    }
}
